export const lightTheme = {
  defaultFontStyle: {
    fontFamily: "Calibre,San Francisco,SF Pro Text",
    fontWeight: "regular",
  },
  palette: {
    themePrimary: "#0408df",
    themeLighterAlt: "#f4f4fe",
    themeLighter: "#d3d3fa",
    themeLight: "#adaef5",
    themeTertiary: "#6163eb",
    themeSecondary: "#1f22e2",
    themeDarkAlt: "#0407c8",
    themeDark: "#0306a9",
    themeDarker: "#02057c",
    neutralLighterAlt: "#f8f8f8",
    neutralLighter: "#f4f4f4",
    neutralLight: "#eaeaea",
    neutralQuaternaryAlt: "#dadada",
    neutralQuaternary: "#d0d0d0",
    neutralTertiaryAlt: "#c8c8c8",
    neutralTertiary: "#b2cebb",
    neutralSecondary: "#739d7f",
    neutralPrimaryAlt: "#436f51",
    neutralPrimary: "#325c3f",
    neutralDark: "#264630",
    black: "#1c3323",
    white: "#ffffff",
  },
};
export const darkTheme = {
  defaultFontStyle: {
    fontFamily: "Calibre,San Francisco,SF Pro Text",
    fontWeight: "regular",
  },
  palette: {
    themePrimary: "#0e8212",
    themeLighterAlt: "#010501",
    themeLighter: "#021503",
    themeLight: "#042705",
    themeTertiary: "#094e0b",
    themeSecondary: "#0d7210",
    themeDarkAlt: "#1c8f20",
    themeDark: "#34a037",
    themeDarker: "#5db960",
    neutralLighterAlt: "#09172d",
    neutralLighter: "#09172c",
    neutralLight: "#09162a",
    neutralQuaternaryAlt: "#081527",
    neutralQuaternary: "#081425",
    neutralTertiaryAlt: "#081324",
    neutralTertiary: "#dce2f8",
    neutralSecondary: "#e2e7f9",
    neutralPrimaryAlt: "#e7ecfa",
    neutralPrimary: "#ccd6f6",
    neutralDark: "#f3f5fd",
    black: "#f9fafe",
    white: "#0a192f",
  },
};
